dataset:
    data_path: '/data/huminyang/dataset/ViperGPT-dataset/vGPT_data/gqa' #vGPT_data/gqa
    # dataset_name: GQA
    split: testdev
    testing: False
    max_samples: 100 # original is 1000, we use 100 for simple testing
    batch_size: 20
    start_sample: 0

prompt : ./prompts/benchmarks/gqa.prompt
results_dir : ./results/gqa/

load_models:
    maskrcnn: True
    clip: False
    glip: True
    owlvit: False
    tcl: False
    gpt3_list: False
    gpt3_qa: True
    gpt3_guess: False
    depth: False
    blip: True
    saliency: False
    xvlm: True

fixed_code_file: ./prompts/fixed_code/blip2.prompt